version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - joelczk
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.2
  - dependency-name: django
    versions:
    - 3.1.6
- package-ecosystem: pip
  directory: "/insecure"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.2
  - dependency-name: django
    versions:
    - 3.1.6
- package-ecosystem: pip
  directory: "/secure"
  schedule:
    interval: weekly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: asgiref
    versions:
    - 3.3.2
  - dependency-name: django
    versions:
    - 3.1.6
    - 3.1.7
