  version: '3.2'

  services:
    insecure:
      build: ./insecure/
      working_dir: /code
      command: python src/manage.py runserver 0.0.0.0:8888
      volumes:
        - type: bind
          source: ./insecure/
          target: /code
      ports:
        - "8000:8888"
    secure:
      build: ./secure/
      working_dir: /code
      command: python src/manage.py runserver 0.0.0.0:8888
      volumes:
        - type: bind
          source: ./secure/
          target: /code
      ports:
        - "8001:8888"