name: Django Security Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FAIL_LEVEL: WARNING
  ENV_TYPE: venv
  DEP_PATH: requirements.txt
  APP_PATH: secure/src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Scan Django settings for security issues
        uses: victoriadrake/django-security-check@master
