name: Git Files scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: Github files AV scan
    steps:
    - uses: actions/checkout@master
    - name: Git AV Scan
      uses: djdefi/gitavscan@master
