name: Static Code Analysis
on:
  push:
    branches: [ master ]
jobs:
  lint:
    name: Run static code analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      uses: devblackops/github-action-psscriptanalyzer@master
      with:
        rootPath: secure
        sendComment: true
        repoToken: ${{ secrets.TOKEN }}
        failOnErrors: true
        failOnWarnings: true
        failOnInfos: true
